
Dataset device: cuda
TRAINING DATA: n=4908319
in_shape = torch.Size([34, 128, 128])
out_shape = torch.Size([10038])
Number of covariates = 34
Number of species = 10038
Dataset device: cuda
VALIDATION: n=85325
in_shape=torch.Size([34, 128, 128])
out_shape=torch.Size([10038]), n_species=10038
MODEL: cnn(
  (conv1): Conv2d(34, 32, kernel_size=(3, 3), stride=(1, 1))
  (act1): ReLU()
  (pool1): MaxPool2d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
  (drop1): Dropout(p=0.3, inplace=False)
  (conv2): Conv2d(32, 8, kernel_size=(3, 3), stride=(1, 1))
  (act2): ReLU()
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (flat): Flatten(start_dim=1, end_dim=-1)
  (fc4): Linear(in_features=3200, out_features=10038, bias=True)
  (act4): ReLU()
)
EPOCH 0
  0%|                                                  | 0/9587 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/nina/Documents/GeoLifeCLEF/simple_cnn.py", line 84, in <module>
    for inputs, labels in tqdm(train_loader):
  File "/home/nina/miniconda3/envs/glc23/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/nina/miniconda3/envs/glc23/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/nina/miniconda3/envs/glc23/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/nina/miniconda3/envs/glc23/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/nina/miniconda3/envs/glc23/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/nina/miniconda3/envs/glc23/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nina/miniconda3/envs/glc23/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nina/miniconda3/envs/glc23/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nina/Documents/GeoLifeCLEF/GLC23Datasets.py", line 101, in __getitem__
    item_targets = torch.from_numpy(item_targets).to(self.device)
  File "/home/nina/miniconda3/envs/glc23/lib/python3.9/site-packages/torch/cuda/__init__.py", line 235, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method